# Generated by Django 4.0.4 on 2022-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project <django.db.models.fields.BigAutoField>', max_length=50),
        ),
    ]
