# Generated by Django 4.0.4 on 2022-08-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectTag',
            new_name='tags',
        ),
    ]
