# Generated by Django 4.0.4 on 2022-08-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_projecttag_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Project Link', 'verbose_name_plural': 'Project Links'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'verbose_name': 'Project Tags', 'verbose_name_plural': 'Project Tags'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AlterField(
            model_name='link',
            name='media',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
