# Generated by Django 4.0.4 on 2022-08-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_link_options_alter_projecttag_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='ProjectLink',
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(to='portfolio.projectlink'),
        ),
    ]
