# Generated by Django 4.0.4 on 2022-08-31 20:49

from django.db import migrations, models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_link_projectlink_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='css_theme',
            field=models.CharField(default='#000', max_length=7, validators=[portfolio.validators.ProjectTag_css_theme_validator]),
        ),
    ]
