# Generated by Django 4.0.4 on 2022-08-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projecttag_css_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttag',
            old_name='css_theme',
            new_name='css_body',
        ),
    ]
