# Generated by Django 4.0.4 on 2022-08-31 22:25

from django.db import migrations, models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_css_theme_projecttag_css_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='css_text',
            field=models.CharField(default='#FFF', max_length=7, validators=[portfolio.validators.ProjectTag_css_theme_validator]),
        ),
    ]
