# Generated by Django 4.0.4 on 2022-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projecttag_css_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='projectlink',
            options={'ordering': ('id',), 'verbose_name': 'Project Link', 'verbose_name_plural': 'Project Links'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'ordering': ('name',), 'verbose_name': 'Project Tags', 'verbose_name_plural': 'Project Tags'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ManyToManyField(to='portfolio.projectmedia'),
        ),
    ]
