name: build_testing

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Initialize .env file
      run: |
        touch .env
        echo django-secret="${{secrets.DJANGO_SECRET}}" >> .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Testing Suite
      run: |
        python manage.py collectstatic --no-input
        python manage.py test
  merge:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git configs
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
        git fetch --unshallow
        git checkout master
        git pulln
        git merge --no-ff staging -m 'Merge staging -> master: ${{github.event.head_commit.message}}'
        git push