name: build_testing

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Initialize .env file
      run: |
        touch .env
        echo django-secret="${{secrets.DJANGO_SECRET}}" >> .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Testing Suite
      run: |
        python manage.py collectstatic --no-input
        python manage.py test
  merge-branch:
    name: Merge `master` back into `develop`
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: merge `master` to `develop`
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: master
        github_token:  ${{ github.token }}