name: build_testing

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Initialize .env file
      run: |
        touch .env
        echo django-secret="${{secrets.DJANGO_SECRET}}" >> .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Testing Suite
      run: |
        python manage.py collectstatic --no-input
        python manage.py test
  merge: 
      needs: [build]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Merge staging -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: 'Merge staging -> master: ${{github.event.head_commit.message}}'
          from_branch: staging
          target_branch: master
          github_token: ${{ github.token }}